<?php

// Directory where the logfiles are located
$config['logdir']   = getcwd() . '/logfiles';

// In this array you can specify real names for the players you want to get statistics from.
$config['players']  = array(
    'Anatoly'       => 'Anatoly',
    'Archangel'     => 'Sven',
    'ArchAngel'     => 'Sven',
    'Schoende'      => 'Sven',
    'Aecrim'        => 'Mircea',
    'Revell'        => 'Jeroen',
    'Enrique'       => 'Enrique',
    'dennis'        => 'Dennis',
    'TT'            => 'Thijs T',
    'Thz'           => 'Thijs Z',
    'Sitting Duck'  => 'Martin',
    'Tamas'         => 'Tamas',
    'Rolph'         => 'Rolph',
    'Gerb'          => 'Gerben',
);

$config['awards'] = array(
    'Gauntlet',
    'Excellent',
    'Impressive',
    'Defense',
    'Capture',
    'Assist',
);

$config['ctf'] = array(
    'Flag taken',
    'Flag captured',
    'Flag returned',
    'Flagcarrier killed',
);

$config['ctfteams'] = array(
    1 => 'Red',
    2 => 'Blue',
);

$config['weapons'] = array(
    'Unknown',
    'Shotgun',
    'Gauntlet',
    'Machinegun',
    'Grenade Launcher',
    'Grenade Launcher (indirect)',
    'Rocket Launcher',
    'Rocket Launcher (indirect)',
    'Plasma Gun',
    'Plasma Gun (indirect)',
    'Railgun',
    'Lightning Gun',
    'BFG',
    'BFG (indirect)',
    'Water',
    'Slime',
    'Lava',
    'Crush',
    'Telefrag',
    'Falling',
    'Suicide',
    'MOD_TARGET_LASER',
    'MOD_TRIGGER_HURT',
    'Nailgun',
    'Chaingun',
    'Proximity Mine',
    'Kamikaze',
    'MOD_JUICED',
    'Grappling Hook',
);

$config['items'] = array(
    'item_armor_shard'          => 'Armor Shard',
    'item_armor_combat'         => 'Armor',
    'item_armor_body'           => 'Heavy Armor',
    'item_health_small'         => '5 Health',
    'item_health'               => '25 Health',
    'item_health_large'         => '50 Health',
    'item_health_mega'          => '100 Health',
    'weapon_gauntlet'           => 'Gauntlet',
    'weapon_shotgun'            => 'Shotgun',
    'weapon_machinegun'         => 'Machinegun',
    'weapon_grenadelauncher'    => 'Grenade Launcher',
    'weapon_rocketlauncher'     => 'Rocket Launcher',
    'weapon_lightning'          => 'Lightning Gun',
    'weapon_railgun'            => 'Railgun',
    'weapon_plasmagun'          => 'Plasma Gun',
    'weapon_bfg'                => 'BFG',
    'weapon_grapplinghook'      => 'Grappling Hook',
    'ammo_shells'               => 'Shells',
    'ammo_bullets'              => 'Bullets',
    'ammo_grenades'             => 'Grenades',
    'ammo_cells'                => 'Cells',
    'ammo_lightning'            => 'Lightning',
    'ammo_rockets'              => 'Rockets',
    'ammo_slugs'                => 'Slugs',
    'ammo_bfg'                  => 'BFG Ammo',
    'holdable_teleporter'       => 'Personal Teleporter',
    'holdable_medkit'           => 'Medkit',
    'item_quad'                 => 'Quad Damage',
    'item_enviro'               => 'Battle Suit',
    'item_haste'                => 'Speed',
    'item_invis'                => 'Invisibility',
    'item_regen'                => 'Regeneration',
    'item_flight'               => 'Flight',
    'team_CTF_redflag'          => 'Red Flag',
    'team_CTF_blueflag'         => 'Blue Flag',
    'holdable_kamikaze'         => 'Kamikaze',
    'holdable_portal'           => 'Portal',
    'holdable_invulnerability'  => 'Invulnerability',
    'ammo_nails'                => 'Nails',
    'ammo_mines'                => 'Proximity Mines',
    'ammo_belt'                 => 'Chaingun Belt',
    'item_scout'                => 'Scout',
    'item_guard'                => 'Guard',
    'item_doubler'              => 'Doubler',
    'item_ammoregen'            => 'Ammo Regen',
    'team_CTF_neutralflag'      => 'Neutral Flag',
    'item_redcube'              => 'Red Cube',
    'item_bluecube'             => 'Blue Cube',
    'weapon_nailgun'            => 'Nailgun',
    'weapon_prox_launcher'      => 'Prox Launcher',
    'weapon_chaingun'           => 'Chaingun',
    'team_DD_pointAblue'        => 'Point A (Blue)',
    'team_DD_pointBblue'        => 'Point B (Blue)',
    'team_DD_pointAred'         => 'Point A (Red)',
    'team_DD_pointBred'         => 'Point B (Red)',
    'team_DD_pointAwhite'       => 'Point A (White)',
    'team_DD_pointBwhite'       => 'Point B (White)',
    'team_dom_pointWhite'       => 'Neutral domination point',
    'team_dom_pointRed'         => 'Red domination point',
    'team_dom_pointBlue'        => 'Blue domination point',
);

$config['challenges'] = array(
   '0'  =>  'GENERAL_TEST',
   '1'  =>  'GENERAL_TOTALKILLS',
   '2'  =>  'GENERAL_TOTALDEATHS',
   '3'  =>  'GENERAL_TOTALGAMES',
 '101'  =>  'GAMETYPES_FFA_WINS',
 '102'  =>  'GAMETYPES_TOURNEY_WINS',
 '103'  =>  'GAMETYPES_TDM_WINS',
 '104'  =>  'GAMETYPES_CTF_WINS',
 '105'  =>  'GAMETYPES_1FCTF_WINS',
 '106'  =>  'GAMETYPES_OVERLOAD_WINS',
 '107'  =>  'GAMETYPES_HARVESTER_WINS',
 '108'  =>  'GAMETYPES_ELIMINATION_WINS',
 '109'  =>  'GAMETYPES_CTF_ELIMINATION_WINS',
 '110'  =>  'GAMETYPES_LMS_WINS',
 '111'  =>  'GAMETYPES_DD_WINS',
 '112'  =>  'GAMETYPES_DOM_WINS',
 '201'  =>  'WEAPON_GAUNTLET_KILLS',
 '202'  =>  'WEAPON_MACHINEGUN_KILLS',
 '203'  =>  'WEAPON_SHOTGUN_KILLS',
 '204'  =>  'WEAPON_GRENADE_KILLS',
 '205'  =>  'WEAPON_ROCKET_KILLS',
 '206'  =>  'WEAPON_LIGHTNING_KILLS',
 '207'  =>  'WEAPON_PLASMA_KILLS',
 '208'  =>  'WEAPON_RAIL_KILLS',
 '209'  =>  'WEAPON_BFG_KILLS',
 '210'  =>  'WEAPON_GRAPPLE_KILLS',
 '211'  =>  'WEAPON_CHAINGUN_KILLS',
 '212'  =>  'WEAPON_NAILGUN_KILLS',
 '213'  =>  'WEAPON_MINE_KILLS',
 '214'  =>  'WEAPON_PUSH_KILLS',
 '215'  =>  'WEAPON_INSTANT_RAIL_KILLS',
 '216'  =>  'WEAPON_TELEFRAG_KILLS',
 '217'  =>  'WEAPON_CRUSH_KILLS',
 '301'  =>  'AWARD_IMPRESSIVE',
 '302'  =>  'AWARD_EXCELLENT',
 '303'  =>  'AWARD_CAPTURE',
 '304'  =>  'AWARD_ASSIST',
 '305'  =>  'AWARD_DEFENCE',
 '401'  =>  'POWERUP_QUAD_KILL',
 '402'  =>  'POWERUP_SPEED_KILL',
 '403'  =>  'POWERUP_FLIGHT_KILL',
 '404'  =>  'POWERUP_INVIS_KILL',
 '405'  =>  'POWERUP_MULTI_KILL',
 '406'  =>  'POWERUP_COUNTER_QUAD',
 '407'  =>  'POWERUP_COUNTER_SPEED',
 '408'  =>  'POWERUP_COUNTER_FLIGHT',
 '409'  =>  'POWERUP_COUNTER_INVIS',
 '410'  =>  'POWERUP_COUNTER_ENVIR',
 '411'  =>  'POWERUP_COUNTER_REGEN',
 '412'  =>  'POWERUP_COUNTER_MULTI',
 '501'  =>  'FFA_TOP3',
 '502'  =>  'FFA_FROMBEHIND',
 '503'  =>  'FFA_BETTERTHAN',
 '504'  =>  'FFA_JUDGE',
 '505'  =>  'FFA_CHEAPKILLER',
);
